### ISSUE TITLE
Include tag

### ISSUE THREAD

**Issue by daslicht** [BigIroh/JooDee#3]
Hello,
I have created the following project:

``` PHP
kiss/
     404.joo    
     500.joo
     app.js
     joodee.joo
     joodee.js
     navigation.joo
```

app.js:

``` PHP
var JooDee = require('./joodee');

var options = {
    name: "demo",
    port: 3000,
    debug: true,
    dir: "./",
    defaultPage: "joodee.joo"
};

var jd = new JooDee.Server(options);
```

joodee.joo

``` PHP
<!DOCTYPE>
<html>
    <head>
        <title>K.I.S.S</title>
    </head>
    <body>
        <::: ./navigation.joo :>
    </body>
</html>
```

This will thow tis error:

``` PHP
error loading include file @ ./navigation.joo 

/Users/daslicht/node/joodee/kiss/joodee.js:254
            var includeDescriptor = content.split('\n').map( function(text) {
                                            ^
TypeError: Object true has no method 'split'
    at exports.Server.addContent (/Users/daslicht/node/joodee/kiss/joodee.js:254:36)
    at includesLoadedCallback (/Users/daslicht/node/joodee/kiss/joodee.js:335:7)
    at exports.Server.includes.(anonymous function) (/Users/daslicht/node/joodee/kiss/joodee.js:308:7)
    at fs.js:117:20
    at Object.oncomplete (fs.js:297:15)

```

I also tried putting my includes in a folder but that did not work either,
What am I missing ?

PS: the concept of JooDee is brilliant ! Thank you very much !

**Comment by mako-taco** [comment]
Thanks for trying the code out! What sites navigation.joo look like?  Both of us have abandoned this project for a more organized approach.. Check out www.github.com/BigIroh/Kyoshi

**Comment by daslicht** [comment]
I just put a div in teh navigation.joo 

now trying : www.github.com/BigIroh/Kyoshi

JooDee was abandoned ?
